package com.backend.model;
// Generated 2017/7/13 ¤W¤È 02:41:10 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * ChatGroup generated by hbm2java
 */
public class ChatGroup implements java.io.Serializable {

	private String cgNo;
	private String cgName;
	private Date cgYear;
	private char cgIsAr;
	private char cgIsAb;
	private char cgIsAc;
	private char cgIsSf;
	private char cgIsAd;
	private String cgBabyRd;

	public ChatGroup() {
	}

	public ChatGroup(String cgNo, String cgName, Date cgYear, char cgIsAr, char cgIsAb, char cgIsAc, char cgIsSf,
			char cgIsAd) {
		this.cgNo = cgNo;
		this.cgName = cgName;
		this.cgYear = cgYear;
		this.cgIsAr = cgIsAr;
		this.cgIsAb = cgIsAb;
		this.cgIsAc = cgIsAc;
		this.cgIsSf = cgIsSf;
		this.cgIsAd = cgIsAd;
	}

	public ChatGroup(String cgNo, String cgName, Date cgYear, char cgIsAr, char cgIsAb, char cgIsAc, char cgIsSf,
			char cgIsAd, String cgBabyRd) {
		this.cgNo = cgNo;
		this.cgName = cgName;
		this.cgYear = cgYear;
		this.cgIsAr = cgIsAr;
		this.cgIsAb = cgIsAb;
		this.cgIsAc = cgIsAc;
		this.cgIsSf = cgIsSf;
		this.cgIsAd = cgIsAd;
		this.cgBabyRd = cgBabyRd;
	}

	public String getCgNo() {
		return this.cgNo;
	}

	public void setCgNo(String cgNo) {
		this.cgNo = cgNo;
	}

	public String getCgName() {
		return this.cgName;
	}

	public void setCgName(String cgName) {
		this.cgName = cgName;
	}

	public Date getCgYear() {
		return this.cgYear;
	}

	public void setCgYear(Date cgYear) {
		this.cgYear = cgYear;
	}

	public char getCgIsAr() {
		return this.cgIsAr;
	}

	public void setCgIsAr(char cgIsAr) {
		this.cgIsAr = cgIsAr;
	}

	public char getCgIsAb() {
		return this.cgIsAb;
	}

	public void setCgIsAb(char cgIsAb) {
		this.cgIsAb = cgIsAb;
	}

	public char getCgIsAc() {
		return this.cgIsAc;
	}

	public void setCgIsAc(char cgIsAc) {
		this.cgIsAc = cgIsAc;
	}

	public char getCgIsSf() {
		return this.cgIsSf;
	}

	public void setCgIsSf(char cgIsSf) {
		this.cgIsSf = cgIsSf;
	}

	public char getCgIsAd() {
		return this.cgIsAd;
	}

	public void setCgIsAd(char cgIsAd) {
		this.cgIsAd = cgIsAd;
	}

	public String getCgBabyRd() {
		return this.cgBabyRd;
	}

	public void setCgBabyRd(String cgBabyRd) {
		this.cgBabyRd = cgBabyRd;
	}

}
