package com.backend.model;
// Generated 2017/7/13 ¤W¤È 02:41:10 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProductClassification generated by hbm2java
 */
public class ProductClassification implements java.io.Serializable {

	private String procNo;
	private String procName;
	private Set<Product> products = new HashSet<Product>(0);

	public ProductClassification() {
	}

	public ProductClassification(String procNo, String procName) {
		this.procNo = procNo;
		this.procName = procName;
	}

	public ProductClassification(String procNo, String procName, Set<Product> products) {
		this.procNo = procNo;
		this.procName = procName;
		this.products = products;
	}

	public String getProcNo() {
		return this.procNo;
	}

	public void setProcNo(String procNo) {
		this.procNo = procNo;
	}

	public String getProcName() {
		return this.procName;
	}

	public void setProcName(String procName) {
		this.procName = procName;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
