package com.backend.model;
// Generated 2017/7/13 ¤W¤È 02:41:10 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.sql.Blob;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private String proNo;
	private Member member;
	private ProductClassification productClassification;
	private Serializable proDate;
	private String proName;
	private int proPrice;
	private Clob proIntro;
	private Blob proPhoto;
	private Blob proPhoto1;
	private Blob proPhoto2;
	private Blob proPhoto3;
	private Blob proPhoto4;
	private Blob proPhoto5;
	private char proStat;
	private char proPay;
	private char proGet;
	private Set<SellerReport> sellerReports = new HashSet<SellerReport>(0);

	public Product() {
	}

	public Product(String proNo, Member member, ProductClassification productClassification, Serializable proDate,
			String proName, int proPrice, Clob proIntro, char proStat, char proPay, char proGet) {
		this.proNo = proNo;
		this.member = member;
		this.productClassification = productClassification;
		this.proDate = proDate;
		this.proName = proName;
		this.proPrice = proPrice;
		this.proIntro = proIntro;
		this.proStat = proStat;
		this.proPay = proPay;
		this.proGet = proGet;
	}

	public Product(String proNo, Member member, ProductClassification productClassification, Serializable proDate,
			String proName, int proPrice, Clob proIntro, Blob proPhoto, Blob proPhoto1, Blob proPhoto2, Blob proPhoto3,
			Blob proPhoto4, Blob proPhoto5, char proStat, char proPay, char proGet, Set<SellerReport> sellerReports) {
		this.proNo = proNo;
		this.member = member;
		this.productClassification = productClassification;
		this.proDate = proDate;
		this.proName = proName;
		this.proPrice = proPrice;
		this.proIntro = proIntro;
		this.proPhoto = proPhoto;
		this.proPhoto1 = proPhoto1;
		this.proPhoto2 = proPhoto2;
		this.proPhoto3 = proPhoto3;
		this.proPhoto4 = proPhoto4;
		this.proPhoto5 = proPhoto5;
		this.proStat = proStat;
		this.proPay = proPay;
		this.proGet = proGet;
		this.sellerReports = sellerReports;
	}

	public String getProNo() {
		return this.proNo;
	}

	public void setProNo(String proNo) {
		this.proNo = proNo;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public ProductClassification getProductClassification() {
		return this.productClassification;
	}

	public void setProductClassification(ProductClassification productClassification) {
		this.productClassification = productClassification;
	}

	public Serializable getProDate() {
		return this.proDate;
	}

	public void setProDate(Serializable proDate) {
		this.proDate = proDate;
	}

	public String getProName() {
		return this.proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public int getProPrice() {
		return this.proPrice;
	}

	public void setProPrice(int proPrice) {
		this.proPrice = proPrice;
	}

	public Clob getProIntro() {
		return this.proIntro;
	}

	public void setProIntro(Clob proIntro) {
		this.proIntro = proIntro;
	}

	public Blob getProPhoto() {
		return this.proPhoto;
	}

	public void setProPhoto(Blob proPhoto) {
		this.proPhoto = proPhoto;
	}

	public Blob getProPhoto1() {
		return this.proPhoto1;
	}

	public void setProPhoto1(Blob proPhoto1) {
		this.proPhoto1 = proPhoto1;
	}

	public Blob getProPhoto2() {
		return this.proPhoto2;
	}

	public void setProPhoto2(Blob proPhoto2) {
		this.proPhoto2 = proPhoto2;
	}

	public Blob getProPhoto3() {
		return this.proPhoto3;
	}

	public void setProPhoto3(Blob proPhoto3) {
		this.proPhoto3 = proPhoto3;
	}

	public Blob getProPhoto4() {
		return this.proPhoto4;
	}

	public void setProPhoto4(Blob proPhoto4) {
		this.proPhoto4 = proPhoto4;
	}

	public Blob getProPhoto5() {
		return this.proPhoto5;
	}

	public void setProPhoto5(Blob proPhoto5) {
		this.proPhoto5 = proPhoto5;
	}

	public char getProStat() {
		return this.proStat;
	}

	public void setProStat(char proStat) {
		this.proStat = proStat;
	}

	public char getProPay() {
		return this.proPay;
	}

	public void setProPay(char proPay) {
		this.proPay = proPay;
	}

	public char getProGet() {
		return this.proGet;
	}

	public void setProGet(char proGet) {
		this.proGet = proGet;
	}

	public Set<SellerReport> getSellerReports() {
		return this.sellerReports;
	}

	public void setSellerReports(Set<SellerReport> sellerReports) {
		this.sellerReports = sellerReports;
	}

}
