package com.backend.model;
// Generated 2017/7/13 ¤W¤È 02:41:10 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;

/**
 * SellerReport generated by hbm2java
 */
public class SellerReport implements java.io.Serializable {

	private SellerReportId id;
	private Member member;
	private Product product;
	private Serializable sellrptDate;
	private String sellrptRsn;
	private char sellrptIsCert;
	private String sellrptUnrsn;

	public SellerReport() {
	}

	public SellerReport(SellerReportId id, Member member, Product product, Serializable sellrptDate, String sellrptRsn,
			char sellrptIsCert) {
		this.id = id;
		this.member = member;
		this.product = product;
		this.sellrptDate = sellrptDate;
		this.sellrptRsn = sellrptRsn;
		this.sellrptIsCert = sellrptIsCert;
	}

	public SellerReport(SellerReportId id, Member member, Product product, Serializable sellrptDate, String sellrptRsn,
			char sellrptIsCert, String sellrptUnrsn) {
		this.id = id;
		this.member = member;
		this.product = product;
		this.sellrptDate = sellrptDate;
		this.sellrptRsn = sellrptRsn;
		this.sellrptIsCert = sellrptIsCert;
		this.sellrptUnrsn = sellrptUnrsn;
	}

	public SellerReportId getId() {
		return this.id;
	}

	public void setId(SellerReportId id) {
		this.id = id;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Serializable getSellrptDate() {
		return this.sellrptDate;
	}

	public void setSellrptDate(Serializable sellrptDate) {
		this.sellrptDate = sellrptDate;
	}

	public String getSellrptRsn() {
		return this.sellrptRsn;
	}

	public void setSellrptRsn(String sellrptRsn) {
		this.sellrptRsn = sellrptRsn;
	}

	public char getSellrptIsCert() {
		return this.sellrptIsCert;
	}

	public void setSellrptIsCert(char sellrptIsCert) {
		this.sellrptIsCert = sellrptIsCert;
	}

	public String getSellrptUnrsn() {
		return this.sellrptUnrsn;
	}

	public void setSellrptUnrsn(String sellrptUnrsn) {
		this.sellrptUnrsn = sellrptUnrsn;
	}

}
