package com.backend.model;
// Generated 2017/7/13 ¤W¤È 02:41:10 by Hibernate Tools 3.5.0.Final

/**
 * SellerReportId generated by hbm2java
 */
public class SellerReportId implements java.io.Serializable {

	private String proNo;
	private String memNo;

	public SellerReportId() {
	}

	public SellerReportId(String proNo, String memNo) {
		this.proNo = proNo;
		this.memNo = memNo;
	}

	public String getProNo() {
		return this.proNo;
	}

	public void setProNo(String proNo) {
		this.proNo = proNo;
	}

	public String getMemNo() {
		return this.memNo;
	}

	public void setMemNo(String memNo) {
		this.memNo = memNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SellerReportId))
			return false;
		SellerReportId castOther = (SellerReportId) other;

		return ((this.getProNo() == castOther.getProNo()) || (this.getProNo() != null && castOther.getProNo() != null
				&& this.getProNo().equals(castOther.getProNo())))
				&& ((this.getMemNo() == castOther.getMemNo()) || (this.getMemNo() != null
						&& castOther.getMemNo() != null && this.getMemNo().equals(castOther.getMemNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProNo() == null ? 0 : this.getProNo().hashCode());
		result = 37 * result + (getMemNo() == null ? 0 : this.getMemNo().hashCode());
		return result;
	}

}
