package com.backend.model;
// Generated 2017/7/13 ¤W¤È 02:41:10 by Hibernate Tools 3.5.0.Final

/**
 * UserReportId generated by hbm2java
 */
public class UserReportId implements java.io.Serializable {

	private String memNoEd;
	private String memNoIng;

	public UserReportId() {
	}

	public UserReportId(String memNoEd, String memNoIng) {
		this.memNoEd = memNoEd;
		this.memNoIng = memNoIng;
	}

	public String getMemNoEd() {
		return this.memNoEd;
	}

	public void setMemNoEd(String memNoEd) {
		this.memNoEd = memNoEd;
	}

	public String getMemNoIng() {
		return this.memNoIng;
	}

	public void setMemNoIng(String memNoIng) {
		this.memNoIng = memNoIng;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserReportId))
			return false;
		UserReportId castOther = (UserReportId) other;

		return ((this.getMemNoEd() == castOther.getMemNoEd()) || (this.getMemNoEd() != null
				&& castOther.getMemNoEd() != null && this.getMemNoEd().equals(castOther.getMemNoEd())))
				&& ((this.getMemNoIng() == castOther.getMemNoIng()) || (this.getMemNoIng() != null
						&& castOther.getMemNoIng() != null && this.getMemNoIng().equals(castOther.getMemNoIng())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMemNoEd() == null ? 0 : this.getMemNoEd().hashCode());
		result = 37 * result + (getMemNoIng() == null ? 0 : this.getMemNoIng().hashCode());
		return result;
	}

}
