package com.backend.model;
// Generated 2017/7/13 ¤W¤È 02:41:10 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.sql.Clob;

/**
 * UserReport generated by hbm2java
 */
public class UserReport implements java.io.Serializable {

	private UserReportId id;
	private Member memberByMemNoIng;
	private Member memberByMemNoEd;
	private Clob urptCnt;
	private Serializable urptDate;
	private String urptRsn;
	private char urptIsCert;
	private String urptUnrsn;

	public UserReport() {
	}

	public UserReport(UserReportId id, Member memberByMemNoIng, Member memberByMemNoEd, Clob urptCnt,
			Serializable urptDate, String urptRsn, char urptIsCert) {
		this.id = id;
		this.memberByMemNoIng = memberByMemNoIng;
		this.memberByMemNoEd = memberByMemNoEd;
		this.urptCnt = urptCnt;
		this.urptDate = urptDate;
		this.urptRsn = urptRsn;
		this.urptIsCert = urptIsCert;
	}

	public UserReport(UserReportId id, Member memberByMemNoIng, Member memberByMemNoEd, Clob urptCnt,
			Serializable urptDate, String urptRsn, char urptIsCert, String urptUnrsn) {
		this.id = id;
		this.memberByMemNoIng = memberByMemNoIng;
		this.memberByMemNoEd = memberByMemNoEd;
		this.urptCnt = urptCnt;
		this.urptDate = urptDate;
		this.urptRsn = urptRsn;
		this.urptIsCert = urptIsCert;
		this.urptUnrsn = urptUnrsn;
	}

	public UserReportId getId() {
		return this.id;
	}

	public void setId(UserReportId id) {
		this.id = id;
	}

	public Member getMemberByMemNoIng() {
		return this.memberByMemNoIng;
	}

	public void setMemberByMemNoIng(Member memberByMemNoIng) {
		this.memberByMemNoIng = memberByMemNoIng;
	}

	public Member getMemberByMemNoEd() {
		return this.memberByMemNoEd;
	}

	public void setMemberByMemNoEd(Member memberByMemNoEd) {
		this.memberByMemNoEd = memberByMemNoEd;
	}

	public Clob getUrptCnt() {
		return this.urptCnt;
	}

	public void setUrptCnt(Clob urptCnt) {
		this.urptCnt = urptCnt;
	}

	public Serializable getUrptDate() {
		return this.urptDate;
	}

	public void setUrptDate(Serializable urptDate) {
		this.urptDate = urptDate;
	}

	public String getUrptRsn() {
		return this.urptRsn;
	}

	public void setUrptRsn(String urptRsn) {
		this.urptRsn = urptRsn;
	}

	public char getUrptIsCert() {
		return this.urptIsCert;
	}

	public void setUrptIsCert(char urptIsCert) {
		this.urptIsCert = urptIsCert;
	}

	public String getUrptUnrsn() {
		return this.urptUnrsn;
	}

	public void setUrptUnrsn(String urptUnrsn) {
		this.urptUnrsn = urptUnrsn;
	}

}
