package com.backend.model;
// Generated 2017/7/13 上午 02:41:10 by Hibernate Tools 3.5.0.Final

import java.sql.Timestamp;


/**
 * Video generated by hbm2java
 */
public class Video implements java.io.Serializable {

	private String vidNo;
	private Baby baby;
	private String vidTitle;
	private Timestamp vidDate;
	private String vidAnnot;
	private byte[] vidFile;
	private String vidShr; // Not Null 0：僅限自己 1：僅限好友 2：公開

	public Video() {
	}

	public Video(String vidNo, Baby baby, Timestamp vidDate, String vidShr) {
		this.vidNo = vidNo;
		this.baby = baby;
		this.vidDate = vidDate;
		this.vidShr = vidShr;
	}

	public Video(String vidNo, Baby baby, String vidTitle, Timestamp vidDate, String vidAnnot, byte[] vidFile,
			String vidShr) {
		this.vidNo = vidNo;
		this.baby = baby;
		this.vidTitle = vidTitle;
		this.vidDate = vidDate;
		this.vidAnnot = vidAnnot;
		this.vidFile = vidFile;
		this.vidShr = vidShr;
	}

	public String getVidNo() {
		return this.vidNo;
	}

	public void setVidNo(String vidNo) {
		this.vidNo = vidNo;
	}

	public Baby getBaby() {
		return this.baby;
	}

	public void setBaby(Baby baby) {
		this.baby = baby;
	}

	public String getVidTitle() {
		return this.vidTitle;
	}

	public void setVidTitle(String vidTitle) {
		this.vidTitle = vidTitle;
	}

	public Timestamp getVidDate() { return this.vidDate; }

	public void setVidDate(Timestamp vidDate) {
		this.vidDate = vidDate;
	}

	public String getVidAnnot() {
		return this.vidAnnot;
	}

	public void setVidAnnot(String vidAnnot) {
		this.vidAnnot = vidAnnot;
	}

	public byte[] getVidFile() {
		return this.vidFile;
	}

	public void setVidFile(byte[] vidFile) {
		this.vidFile = vidFile;
	}

	public String getVidShr() {
		return this.vidShr;
	}

	public void setVidShr(String vidShr) {
		this.vidShr = vidShr;
	}

}
