package com.backend.model;
// Generated 2017/7/13 ¤W¤È 02:41:10 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.sql.Clob;

/**
 * Answer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

	private String ansNo;
	private Member member;
	private Question question;
	private Serializable ansDate;
	private Clob ansCnt;
	private int ansLike;
	private char ansIsHide;

	public Answer() {
	}

	public Answer(String ansNo, Member member, Question question, Serializable ansDate, Clob ansCnt, int ansLike,
			char ansIsHide) {
		this.ansNo = ansNo;
		this.member = member;
		this.question = question;
		this.ansDate = ansDate;
		this.ansCnt = ansCnt;
		this.ansLike = ansLike;
		this.ansIsHide = ansIsHide;
	}

	public String getAnsNo() {
		return this.ansNo;
	}

	public void setAnsNo(String ansNo) {
		this.ansNo = ansNo;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public Serializable getAnsDate() {
		return this.ansDate;
	}

	public void setAnsDate(Serializable ansDate) {
		this.ansDate = ansDate;
	}

	public Clob getAnsCnt() {
		return this.ansCnt;
	}

	public void setAnsCnt(Clob ansCnt) {
		this.ansCnt = ansCnt;
	}

	public int getAnsLike() {
		return this.ansLike;
	}

	public void setAnsLike(int ansLike) {
		this.ansLike = ansLike;
	}

	public char getAnsIsHide() {
		return this.ansIsHide;
	}

	public void setAnsIsHide(char ansIsHide) {
		this.ansIsHide = ansIsHide;
	}

}
