package com.backend.model;
// Generated 2017/7/13 ¤W¤È 02:41:10 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Baby generated by hbm2java
 */
public class Baby implements java.io.Serializable {

	private String babyNo;
	private Member member;
	private String babyAka;
	private Date babyBday;
	private String babyGen;
	private BigDecimal babyHc;
	private BigDecimal babyHt;
	private BigDecimal babyWt;
	private String babyIsAr;
	private String babyIsAb;
	private String babyIsAc;
	private String babyIsSf;
	private String babyIsAd;
	private String babyRd;
	private Set<Video> videos = new HashSet<Video>(0);

	public Baby() {
	}

	public Baby(String babyNo, Member member, String babyAka, Date babyBday, String babyGen, BigDecimal babyHc,
			BigDecimal babyHt, BigDecimal babyWt, String babyIsAr, String babyIsAb, String babyIsAc, String babyIsSf,
			String babyIsAd) {
		this.babyNo = babyNo;
		this.member = member;
		this.babyAka = babyAka;
		this.babyBday = babyBday;
		this.babyGen = babyGen;
		this.babyHc = babyHc;
		this.babyHt = babyHt;
		this.babyWt = babyWt;
		this.babyIsAr = babyIsAr;
		this.babyIsAb = babyIsAb;
		this.babyIsAc = babyIsAc;
		this.babyIsSf = babyIsSf;
		this.babyIsAd = babyIsAd;
	}

	public Baby(String babyNo, Member member, String babyAka, Date babyBday, String babyGen, BigDecimal babyHc,
			BigDecimal babyHt, BigDecimal babyWt, String babyIsAr, String babyIsAb, String babyIsAc, String babyIsSf,
			String babyIsAd, String babyRd, Set<Video> videos) {
		this.babyNo = babyNo;
		this.member = member;
		this.babyAka = babyAka;
		this.babyBday = babyBday;
		this.babyGen = babyGen;
		this.babyHc = babyHc;
		this.babyHt = babyHt;
		this.babyWt = babyWt;
		this.babyIsAr = babyIsAr;
		this.babyIsAb = babyIsAb;
		this.babyIsAc = babyIsAc;
		this.babyIsSf = babyIsSf;
		this.babyIsAd = babyIsAd;
		this.babyRd = babyRd;
		this.videos = videos;
	}

	public String getBabyNo() {
		return this.babyNo;
	}

	public void setBabyNo(String babyNo) {
		this.babyNo = babyNo;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getBabyAka() {
		return this.babyAka;
	}

	public void setBabyAka(String babyAka) {
		this.babyAka = babyAka;
	}

	public Date getBabyBday() {
		return this.babyBday;
	}

	public void setBabyBday(Date babyBday) {
		this.babyBday = babyBday;
	}

	public String getBabyGen() {
		return this.babyGen;
	}

	public void setBabyGen(String babyGen) {
		this.babyGen = babyGen;
	}

	public BigDecimal getBabyHc() {
		return this.babyHc;
	}

	public void setBabyHc(BigDecimal babyHc) {
		this.babyHc = babyHc;
	}

	public BigDecimal getBabyHt() {
		return this.babyHt;
	}

	public void setBabyHt(BigDecimal babyHt) {
		this.babyHt = babyHt;
	}

	public BigDecimal getBabyWt() {
		return this.babyWt;
	}

	public void setBabyWt(BigDecimal babyWt) {
		this.babyWt = babyWt;
	}

	public String getBabyIsAr() {
		return this.babyIsAr;
	}

	public void setBabyIsAr(String babyIsAr) {
		this.babyIsAr = babyIsAr;
	}

	public String getBabyIsAb() {
		return this.babyIsAb;
	}

	public void setBabyIsAb(String babyIsAb) {
		this.babyIsAb = babyIsAb;
	}

	public String getBabyIsAc() {
		return this.babyIsAc;
	}

	public void setBabyIsAc(String babyIsAc) {
		this.babyIsAc = babyIsAc;
	}

	public String getBabyIsSf() {
		return this.babyIsSf;
	}

	public void setBabyIsSf(String babyIsSf) {
		this.babyIsSf = babyIsSf;
	}

	public String getBabyIsAd() {
		return this.babyIsAd;
	}

	public void setBabyIsAd(String babyIsAd) {
		this.babyIsAd = babyIsAd;
	}

	public String getBabyRd() {
		return this.babyRd;
	}

	public void setBabyRd(String babyRd) {
		this.babyRd = babyRd;
	}

	public Set<Video> getVideos() {
		return this.videos;
	}

	public void setVideos(Set<Video> videos) {
		this.videos = videos;
	}

}
