package com.backend.model;
// Generated 2017/7/13 ¤W¤È 02:41:10 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member implements java.io.Serializable {

	private String memNo;
	private String expNo;
	private String memgGr;
	private String memAcct;
	private String memPwd;
	private Date memJoind;
	private Date memUpdated;
	private String memName;
	private String memAka;
	private byte[] memPhoto;
	private String memAdds;
	private String memAddc;
	private String memPhone;
	private String memMail;
	private String memIntroB;
	private String memIsSell;
	private String memAcctS;
	private String memIntroS;
	private String memPointS;
	private String memIntroE;
	private String memIsStop;
	private String memPointB;
	private Set<Baby> babies = new HashSet<Baby>(0);
	private Set<ChatFriend> chatFriendsForMemNoS = new HashSet<ChatFriend>(0);
	private Set<ChatFriend> chatFriendsForMemNoO = new HashSet<ChatFriend>(0);
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<Article> articles = new HashSet<Article>(0);
	private Set<Product> products = new HashSet<Product>(0);
	private Set<SellerReport> sellerReports = new HashSet<SellerReport>(0);
	private Set<UserReport> userReportsForMemNoEd = new HashSet<UserReport>(0);
	private Set<UserReport> userReportsForMemNoIng = new HashSet<UserReport>(0);
	private Set<Answer> answers = new HashSet<Answer>(0);

	public Member() {
	}

	public Member(String memNo, String memgGr, String memAcct, String memPwd, Date memJoind, String memName,
			String memAdds, String memIsSell, String memIsStop) {
		this.memNo = memNo;
		this.memgGr = memgGr;
		this.memAcct = memAcct;
		this.memPwd = memPwd;
		this.memJoind = memJoind;
		this.memName = memName;
		this.memAdds = memAdds;
		this.memIsSell = memIsSell;
		this.memIsStop = memIsStop;
	}

	public Member(String memNo, String expNo, String memgGr, String memAcct, String memPwd, Date memJoind,
			Date memUpdated, String memName, String memAka, byte[] memPhoto, String memAdds, String memAddc,
			String memPhone, String memMail, String memIntroB, String memIsSell, String memAcctS, String memIntroS,
			String memPointS, String memIntroE, String memIsStop, String memPointB, Set<Baby> babies,
			Set<ChatFriend> chatFriendsForMemNoS, Set<ChatFriend> chatFriendsForMemNoO, Set<Question> questions,
			Set<Article> articles, Set<Product> products, Set<SellerReport> sellerReports,
			Set<UserReport> userReportsForMemNoEd, Set<UserReport> userReportsForMemNoIng, Set<Answer> answers) {
		this.memNo = memNo;
		this.expNo = expNo;
		this.memgGr = memgGr;
		this.memAcct = memAcct;
		this.memPwd = memPwd;
		this.memJoind = memJoind;
		this.memUpdated = memUpdated;
		this.memName = memName;
		this.memAka = memAka;
		this.memPhoto = memPhoto;
		this.memAdds = memAdds;
		this.memAddc = memAddc;
		this.memPhone = memPhone;
		this.memMail = memMail;
		this.memIntroB = memIntroB;
		this.memIsSell = memIsSell;
		this.memAcctS = memAcctS;
		this.memIntroS = memIntroS;
		this.memPointS = memPointS;
		this.memIntroE = memIntroE;
		this.memIsStop = memIsStop;
		this.memPointB = memPointB;
		this.babies = babies;
		this.chatFriendsForMemNoS = chatFriendsForMemNoS;
		this.chatFriendsForMemNoO = chatFriendsForMemNoO;
		this.questions = questions;
		this.articles = articles;
		this.products = products;
		this.sellerReports = sellerReports;
		this.userReportsForMemNoEd = userReportsForMemNoEd;
		this.userReportsForMemNoIng = userReportsForMemNoIng;
		this.answers = answers;
	}

	public String getMemNo() {
		return this.memNo;
	}

	public void setMemNo(String memNo) {
		this.memNo = memNo;
	}

	public String getExpNo() {
		return this.expNo;
	}

	public void setExpNo(String expNo) {
		this.expNo = expNo;
	}

	public String getMemgGr() {
		return this.memgGr;
	}

	public void setMemgGr(String memgGr) {
		this.memgGr = memgGr;
	}

	public String getMemAcct() {
		return this.memAcct;
	}

	public void setMemAcct(String memAcct) {
		this.memAcct = memAcct;
	}

	public String getMemPwd() {
		return this.memPwd;
	}

	public void setMemPwd(String memPwd) {
		this.memPwd = memPwd;
	}

	public Date getMemJoind() {
		return this.memJoind;
	}

	public void setMemJoind(Date memJoind) {
		this.memJoind = memJoind;
	}

	public Date getMemUpdated() {
		return this.memUpdated;
	}

	public void setMemUpdated(Date memUpdated) {
		this.memUpdated = memUpdated;
	}

	public String getMemName() {
		return this.memName;
	}

	public void setMemName(String memName) {
		this.memName = memName;
	}

	public String getMemAka() {
		return this.memAka;
	}

	public void setMemAka(String memAka) {
		this.memAka = memAka;
	}

	public byte[] getMemPhoto() {
		return this.memPhoto;
	}

	public void setMemPhoto(byte[] memPhoto) {
		this.memPhoto = memPhoto;
	}

	public String getMemAdds() {
		return this.memAdds;
	}

	public void setMemAdds(String memAdds) {
		this.memAdds = memAdds;
	}

	public String getMemAddc() {
		return this.memAddc;
	}

	public void setMemAddc(String memAddc) {
		this.memAddc = memAddc;
	}

	public String getMemPhone() {
		return this.memPhone;
	}

	public void setMemPhone(String memPhone) {
		this.memPhone = memPhone;
	}

	public String getMemMail() {
		return this.memMail;
	}

	public void setMemMail(String memMail) {
		this.memMail = memMail;
	}

	public String getMemIntroB() {
		return this.memIntroB;
	}

	public void setMemIntroB(String memIntroB) {
		this.memIntroB = memIntroB;
	}

	public String getMemIsSell() {
		return this.memIsSell;
	}

	public void setMemIsSell(String memIsSell) {
		this.memIsSell = memIsSell;
	}

	public String getMemAcctS() {
		return this.memAcctS;
	}

	public void setMemAcctS(String memAcctS) {
		this.memAcctS = memAcctS;
	}

	public String getMemIntroS() {
		return this.memIntroS;
	}

	public void setMemIntroS(String memIntroS) {
		this.memIntroS = memIntroS;
	}

	public String getMemPointS() {
		return this.memPointS;
	}

	public void setMemPointS(String memPointS) {
		this.memPointS = memPointS;
	}

	public String getMemIntroE() {
		return this.memIntroE;
	}

	public void setMemIntroE(String memIntroE) {
		this.memIntroE = memIntroE;
	}

	public String getMemIsStop() {
		return this.memIsStop;
	}

	public void setMemIsStop(String memIsStop) {
		this.memIsStop = memIsStop;
	}

	public String getMemPointB() {
		return this.memPointB;
	}

	public void setMemPointB(String memPointB) {
		this.memPointB = memPointB;
	}

	public Set<Baby> getBabies() {
		return this.babies;
	}

	public void setBabies(Set<Baby> babies) {
		this.babies = babies;
	}

	public Set<ChatFriend> getChatFriendsForMemNoS() {
		return this.chatFriendsForMemNoS;
	}

	public void setChatFriendsForMemNoS(Set<ChatFriend> chatFriendsForMemNoS) {
		this.chatFriendsForMemNoS = chatFriendsForMemNoS;
	}

	public Set<ChatFriend> getChatFriendsForMemNoO() {
		return this.chatFriendsForMemNoO;
	}

	public void setChatFriendsForMemNoO(Set<ChatFriend> chatFriendsForMemNoO) {
		this.chatFriendsForMemNoO = chatFriendsForMemNoO;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	public Set<SellerReport> getSellerReports() {
		return this.sellerReports;
	}

	public void setSellerReports(Set<SellerReport> sellerReports) {
		this.sellerReports = sellerReports;
	}

	public Set<UserReport> getUserReportsForMemNoEd() {
		return this.userReportsForMemNoEd;
	}

	public void setUserReportsForMemNoEd(Set<UserReport> userReportsForMemNoEd) {
		this.userReportsForMemNoEd = userReportsForMemNoEd;
	}

	public Set<UserReport> getUserReportsForMemNoIng() {
		return this.userReportsForMemNoIng;
	}

	public void setUserReportsForMemNoIng(Set<UserReport> userReportsForMemNoIng) {
		this.userReportsForMemNoIng = userReportsForMemNoIng;
	}

	public Set<Answer> getAnswers() {
		return this.answers;
	}

	public void setAnswers(Set<Answer> answers) {
		this.answers = answers;
	}

}
